name: docker-v7-manual-push

on: [push]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set lower case owner name
        id: lc_owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        run: |
          docker build -t deni1743/passivbot:nightly -f _Dockerfile .
          docker tag deni1743/passivbot:nightly ghcr.io/${{ env.OWNER_LC }}/passivbot:nightly
          docker push ghcr.io/${{ env.OWNER_LC }}/passivbot:nightly
